### ISSUE TITLE
TypeInitializationException - The type initializer for ...ShadedCard threw an exception

### ISSUE THREAD

**Issue by pskyv** [Intelliabb/XamCustomLayouts#1]
Hi, I try to use your ShadedCard control in one of my projects.
I try to show a content page whose content is set like this:

<FlexLayout Direction="Column"
                AlignItems="Center"
                JustifyContent="SpaceEvenly">

        <controls:ShadedCard HasShadow="True" CornerRadius="0" Title="This is a card">
            <controls:ShadedCard.CardContent>
                <Label Text="This is the content..." />
            </controls:ShadedCard.CardContent>
            <controls:ShadedCard.ActionView>
                <Button Text="Action" />
            </controls:ShadedCard.ActionView>
        </controls:ShadedCard> 
        
    </FlexLayout>

When the constructor of the page is called I get the following runtime exception:
"Exception occurred while: Calling constructor DentalAssistantXF.Views.MainPage().
Exception is: TypeInitializationException - The type initializer for 'DentalAssistantXF.Controls.ShadedCard' threw an exception."

If i remove the ShadedCard control the application doesn't crash.

I would appreciate any kind of help

**Comment by hnabbasi** [comment]
Looks like one of your bindable property is getting a wrong value type set, maybe as default. Can you look deeper in the exception and post the stack trace?

**Comment by pskyv** [comment]
Ok I found it
I kept the default value you are using for the TitleStyleProperty but it was missing from my solution.
Thanks for your help
